### ISSUE TITLE
WBPaper00053739- drosophila not extracted

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_pipeline#13]
Mentioned 5x: 3 in main text, 2 in references

**Comment by valearna** [comment]
the keyword "drosophila" appears in the text, but our regular expressions search for the following cases:

- Drosophila melanogaster
- D. melanogaster
- fruitfly
- fruitflies

which are not in the text. If we change the general rule and search for "drosophila" as well, we would also match, for example, all the Caenorhabditis species every time we find "caenorhabditis" in the text. Is this what we want?

**Comment by draciti** [comment]
@vanaukenk, what do you think? Should we add the generic 'drosophila' and 'caenorhabditis' terms in the regular expressions search?

**Comment by vanaukenk** [comment]
@draciti @valearna 
I am wondering if the intended meaning of a genus term in the literature might depend on what literature we're looking at, i.e. in the C. elegans literature Drosophila probably means Drosophila melanogaster while Caenorhabditis probably refers more generally to the genus and not just C. elegans.
I think I would opt for keeping our search as is for now, but Daniela for this paper would we then miss that Drosophila melanogaster was one of the main species studied?

**Comment by draciti** [comment]
it was not the main species studied. I agree keeping the search as is. Closing
