### ISSUE TITLE
calculate statistics for a large sample of papers

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#18]
We need to calculate the average number of entities identified in the papers to validate the thresholds

**Comment by valearna** [comment]
I added an option to the pipeline to print stats of the processed papers instead of saving the extracted info to db. These are the results for the latest 100 processed papers (i.e., papers that have fulltext and a recognized email address):

Statistics calculated on the latest set of 100 papers that can be processed by AFP
Number of papers with non-empty entity lists (at least one recognized entity among genes, species, transgenes, alleles, and strains): 96
Average number of genes extracted: 8.76
Average number of species extracted: 1.32
Average number of alleles extracted: 3.27
Average number of transgenes extracted: 1.52
Average number of strains extracted: 4.0

**Comment by valearna** [comment]
I also debugged the first ten papers in the queue - the newest with svm results - and I found that the pdf2text conversion works quite well and all the papers that can't be processed are _tmp files containing only the abstract, which are discarded for they lack an email address.

**Comment by vanaukenk** [comment]
Thanks @valearna  It's really nice to have some statistics for this.
Maybe we can add the numbers next to each of the entities listed in the text box and the information about papers processed to the overview box?

**Comment by valearna** [comment]
Thanks @vanaukenk. I added the numbers to the poster. Feel free to change the text.

**Comment by valearna** [comment]
We will continue monitoring these numbers over time to make sure that final pdf versions are correctly processed

**Comment by valearna** [comment]
the stats are now included in the afp dashboard and are dynamically populated so that we can monitor them over time. I'm closing this issue
