### ISSUE TITLE
save afp_species list in pap_species

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#24]
- merge existing data with new one - keep existing data and do not replicate rows with afp data. Add afp data if not already present
- no evidence
- use taxon id and put order at the end
- do we need to create a person id for afp? - we need to change the pipeline and process only papers that have an email address linked to a person ID. We can test all addresses in the paper and if none is linked to a person ID we skip the paper
- save information to h_pap_species as well - when deleting data we have to add new records with blank lines (pap_gene column set to null)

**Comment by valearna** [comment]
http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/phenotype.cgi?action=autocompleteXHR&field=person&query=bob

http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/phenotype.cgi?action=asyncTermInfo&field=person&termid=WBPerson3528

Combine these API calls in a new component to select the person ID with which results will be saved

**Comment by valearna** [comment]
save pap_curator in the form 'two\<PersonID\>' instead of 'WBPerson\<PersonID\>'

**Comment by valearna** [comment]
The table pap_species doesn't have a field for evidence codes. Keeping track of the species when authors save the AFP form multiple time after removing previously selected species is quite complicated. Can we add a pap_evidence field as in the pap_gene table @azurebrd ?

**Comment by azurebrd** [comment]
Resolved in emails.  The ?Paper -> ?Gene connection in the acedb model has an #Evidence while ?Paper -> ?Species doesn't, so we'll do updates based on paper-curator-data
