### ISSUE TITLE
'Strain' keyword found in strains identified in the paper 00049183

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#29]

**Comment by valearna** [comment]
The keyword 'Strain' is in the obo_name_strain table both on tazendra and mangolassi. Should we remove it from the table @vanaukenk? Alternatively we can create a filter to exclude it from the pipeline

**Comment by vanaukenk** [comment]
@valearna - since I don't curate strains,  I don't know if that entry in the 'Strain' table serves any curatorial purpose.  I think the best thing to do is ask as today's Caltech meeting and then proceed from there.  Thx.

**Comment by vanaukenk** [comment]
http://wiki.wormbase.org/index.php/WormBase-Caltech_Weekly_Calls#January_24th.2C_2019

**Comment by valearna** [comment]
This was a bug in the source data that has been fixed by Paul Davis. Closing
