### ISSUE TITLE
save results to DB

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#3]
save data from each page separately

**Comment by valearna** [comment]
I can set up a Python API to write the results to DB and host the API on textpressocentral together with the pipeline. In this way all the AFP code will remain in the same repository and it will be easier to maintain. What do you think @azurebrd?

**Comment by azurebrd** [comment]
Sure thing @valearna !  I would have been good to write a web API that you could post to, but if the python API can write to postgres directly, that's great too.

**Comment by vanaukenk** [comment]
Check site and time of action also once those tables are added to the curation status form.
