### ISSUE TITLE
extract papers from production pipeline for testing

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#37]
create a file with 50 papers with paper ID, title, journal, and list of authors

**Comment by valearna** [comment]
[list_papers.txt](https://github.com/WormBase/afp_pipeline/files/2881130/list_papers.txt)
This is the list of papers updated today - Paper ID only

**Comment by valearna** [comment]
[list_papers_title.txt](https://github.com/WormBase/afp_pipeline/files/2881740/list_papers_title.txt)

List with title and journal - still working to get the list of authors

**Comment by valearna** [comment]
[list_papers_authors.txt](https://github.com/WormBase/afp_pipeline/files/2881776/list_papers_authors.txt)

Authors included

**Comment by valearna** [comment]
put journal in first column and aggregate authors

**Comment by vanaukenk** [comment]
56034
56035
56039
56046
56066
56073
56075
56080
56090
56091
56095
56096

**Comment by draciti** [comment]
56031

**Comment by valearna** [comment]
curatable_papers_not_processed_svm_flagged = ["00056034", "00056035", "00056039", "00056046", "00056066", "00056073", "00056075", "00056080", "00056090", "00056091", "00056095", "00056096", "00056031"]
