### ISSUE TITLE
wrong species extracted

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#38]
Species with a single word keyword (e.g., catfish) are extracted even though there are no matches in the text. This is due to the two-words regex rule (i.e., add "M. musculus" to the regex to search when species is  "Mus musculus") being added also to one-word species.

**Comment by valearna** [comment]
issue solved. Leaving open for testing

**Comment by draciti** [comment]
Solved for me, leaving open for @vanaukenk testing

**Comment by vanaukenk** [comment]
All seems fine with my testing papers, so I will close this issue.
