### ISSUE TITLE
Genes with multiple matches (e.g. Cre-51.1, Cre-51.2)

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_pipeline#4]
For WBPaper00050093 Cre-51 is mentioned in the paper but Cre-51.2 is extracted (not also Cre-51.1). Find a way to extract both

**Comment by draciti** [comment]
fixed

**Comment by vanaukenk** [comment]
Just a note from re-checking this paper - Cre-rad-51.2 _is_ mentioned in the text and we get the correct match in the AFP form.
