### ISSUE TITLE
Some species are almost always extracted

### ISSUE THREAD

**Issue by valearna** [WormBase/afp_pipeline#40]
Homo sapiens and mouse are almost always mentioned in the text. We talked about increasing the threshold to 10 for species or using a different threshold for species with multiple aliases.

**Comment by vanaukenk** [comment]
A threshold of 10 would work for the three new papers I tested.

**Comment by valearna** [comment]
we decided to increase the threshold to 10. Change it both in the pipeline and in the tooltip message

**Comment by draciti** [comment]
Tested on 

- WBPaper00056091 -> ok extracted only C elegans and not anymore human
- WBPaper00056039 -> ok extracted only C elegans and not anymore human
- WBPaper00056080 -> C elegans no longer extracted -> 23 matches

@valerio, can you take a look at WBPaper00056080?

**Comment by valearna** [comment]
I checked WBPaper00056080 and I found that most of the matches contain a double white space (i.e. "C.  elegans). I will remove multiple whitespaces in the text and process the papers again

**Comment by valearna** [comment]
New form ready for testing
