### ISSUE TITLE
Matching gene synonyms now produces false positives

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_pipeline#44]
Looking for matches to gene synonyms from the gin_synonyms table, now produces false positives in the gene lists.

For the six papers in testing:

56039 - TOR (WBGene00002583)

56066 - Ny (WBGene00003066)
56066 - SL2 (WBGene00004836)
56066 - eT1 (WBGene00006772)

56075 - B1 (WBGene00002053)

56080 - JP (WBGene00002179)
56080 - M3 (WBGene00249437)

56091 - no false positives

56095 - CAT (WBGene00000831)
56095 - M3 (WBGene00249437)

I still need to double-check if looking for synonyms is retrieving true positive genes that we missed before.

**Comment by vanaukenk** [comment]
hdac-6, synonym for hda-6 and mentioned 37 times in 56039, is now returned.

**Comment by draciti** [comment]
I still see false positives

**Comment by valearna** [comment]
We still need to discuss this issue before I can modify the code again @draciti. The new version of the pipeline extracts a gene if its sysonyms are mentioned in the text, even if the gene itself is never mentioned. I thought this was what we wanted, but maybe I got it wrong. If we want to recognize genes and their synonyms as separate entities what should we do if we have mentions to both the main gene and their synonyms?

**Comment by valearna** [comment]
We decided to remove synonyms from the list
