### ISSUE TITLE
Check supplementals for WBPaper00053873

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_pipeline#5]
http://tazendra.caltech.edu/~acedb/daniel/00053873/41467_2018_3531_MOESM1_ESM.pdf

Check how the tables in this supplemental file are extracted. Strains are not extracted in AFP. Is the content available in TP?

**Comment by valearna** [comment]
with the changes introduced in #2 some of the "good" supplemental material was removed as well. I'm working to put it back @draciti

**Comment by draciti** [comment]
Strains extracted properly. Closing
