### ISSUE TITLE
Genes not extracted -with more than one occurrence

### ISSUE THREAD

**Issue by draciti** [WormBase/afp_pipeline#8]
Only 3 genes were not extracted (and were supposed to) this time around. All the other genes were fine (34 genes total)

**_taf-1_**
Sentence 1 in Main text: ". **taf-1** encoding an ortholog of human TATA-binding protein associated factor TAF1L"
Sentence 2 in supplementals: "the promoter region of **taf-1** and myo-2 were served as the negative and positive" 

**_eat-2_**
Mentioned 3x in main text: 'To rule out this possibility, we examined **eat-2**, which encodes a nicotinic acetylcholine receptor subunit that functions in the pharyngeal muscle, the mutation of which led to a feeding defect with reduced pharyngeal pump- ing40,41. Although **eat-2**(ad465) mutant worms showed obviously decreased lipid accumulation compared with WT worms, their TAG content and LD size still increased in the rrp-8(kun54) mutant background (Supplementary Fig. 6A–C). Thus, the suppression of nucleolar stress-induced lipid accumulation is probably not a result of a feeding defect in in pha-4(zu225) mutant, even though the phenotype of pha-4 mutant is stronger than **eat-2** mutant. 

Mentioned 1x in supplementals: 'The increased lipid accumulation in rrp-8(kun54) worms is independent of **eat-2**.'

**myo-2**
Mentioned 1x in main text: '**myo-2** encoding a muscle-type-specific myosin heavy chain isoform were previously '

Mentioned 1x in supplementals: 'the promoter region of taf-1 and **myo-2** were served as the negative and positive control'

**Comment by draciti** [comment]
Forgot to add the Paper: WBPaper00053873

**Comment by vanaukenk** [comment]
For WBPaper00054889 -
There is one gene, gsa-1, that appears >2 times but only in figures 1 and 4, and it is not extracted.  
Perhaps this is due to the way that it appears in the figures, i.e. within a cartoon of the signaling pathway.

**Comment by valearna** [comment]
I fixed the TPC bug that was removing part of the text from the documents (in the lucene index) and now eat-2 is correctly identified. For taf-1 and myo-2 the problem still remains and is different: it is related to the cas files, not the index. I will test the other genes and alleles too. I need to re-run the pipeline again and create new links to the form. I will move these issues (also #9 and #10) to 'Need testing' once the links are ready.

**Comment by draciti** [comment]
I confirm eat-2 is extracted. taf-1 and myo-2 still missing. Valerio, should I ignore them as they are not in the cas-files? or you want me to check on TPC?

**Comment by valearna** [comment]
thanks @draciti  I've already checked on TPC and taf-1 and myo-2 are not there. I would ignore them for now.

**Comment by draciti** [comment]
ok, will close this for now
