### ISSUE TITLE
Alleles not extracted - with more than one occurrence

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/afp_pipeline#9]
For WBPaper00054889 there is one allele, lst34 (WBVar01429503) that is mentioned once in a Supplementary table and several times in figures in the main text (e.g. Figure 1).

Perhaps the mentions in the Figure are not detected, so it's not reaching the threshold value we set for alleles.

This may be similar to the issue of gsa-1 mentions in figures that were not detected from this same paper, described in #8

**Comment by valearna** [comment]
I found only one mention in the text indexed by TPC. The mentions in the figures are probably lost during pdf to cas conversion. Need more testing

**Comment by valearna** [comment]
I opened the main text in TPC and did not find any mention to the allele. This means that it is not in the cas file and must have been removed during pdf->cas conversion.
